<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.anurag</groupId>
    <artifactId>certificate-app</artifactId>
    <version>1.0</version>
    <packaging>war</packaging> m

    <properties>
        <sonar.host.url>http://13.210.14.138:9000/</sonar.host.url>
    </properties>

   <distributionManagement>
    <repository>
        <id>nexus</id>
        <url>http://13.232.183.130:8081/repository/amazon-release/</url>
    </repository>

    <snapshotRepository>
        <id>nexus</id>
        <url>http://13.232.183.130:8081/repository/amazon-Snapshot/</url>
    </snapshotRepository>
   </distributionManagement>

    <build>
        <finalName>certificate-app</finalName>
       
        <plugins>
       <plugin>
                  <groupId>org.sonarsource.scanner.maven</groupId>
                  <artifactId>sonar-maven-plugin</artifactId>
                  <version>5.3.0.6276</version>                                                             
                  </plugin> 
        <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
        </plugin>
        </plugins>
    </build>

</project>
